version: "2"
services:
  phoenix:
    build: .
    depends_on:
      - db    
    ports:
      - 4000:4000    
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
