version: "2"
services:
  phoenix:
    image: connormckelvey/phoenix
    ports:
      - 4000:4000        
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
